package com.coinnote.entryservice.mapper;

import com.coinnote.entryservice.dto.housing.HousingDto;
import com.coinnote.entryservice.dto.mobility.MobilityDto;
import com.coinnote.entryservice.entity.AccountingTypes;
import com.coinnote.entryservice.entity.housing.HousingInstance;
import com.coinnote.entryservice.entity.mobility.MobilityInstance;
import org.mapstruct.*;

/*
@Mapper(componentModel = "spring")
public interface DataMapper<I extends CommonInstance, D extends CommonDto> {

    //Maps: id, title
    I mapDtoToInstance(D dto, User user);

    D mapInstanceToDto(I instance);


}
 */

@Mapper(componentModel = "spring")
public abstract class DataMapper {

    //Maps: id, title


    //TODO: check mapper instance is not autogenerated

    //@Mapping(target = "accountSpentService", ignore=true)
    //@Mapping(target = "accountSpentPetrol", ignore=true)
    //@Mapping(target = "accountSpentParts", ignore=true)
    //@Mapping(target = "totalSpending", ignore=true)
    public abstract MobilityInstance map(MobilityDto dto, String userName);
    public abstract HousingInstance map(HousingDto dto, String userName);

    public abstract MobilityDto map(MobilityInstance mobilityInstance);
    public abstract HousingDto map(HousingInstance housingInstance);


    @AfterMapping
    protected void mapAutoAccountUpdates(MobilityDto dto,
                                         @MappingTarget final MobilityInstance mobilityInstance){

        mobilityInstance.getAccountSpentService().put(AccountingTypes.w.toString(), dto.serviceSpending.longValue());
        mobilityInstance.getAccountSpentService().put(AccountingTypes.m.toString(), dto.serviceSpending.longValue());
        mobilityInstance.getAccountSpentService().put(AccountingTypes.y.toString(), dto.serviceSpending.longValue());

        mobilityInstance.getAccountSpentPetrol().put(AccountingTypes.w.toString(), dto.petrolSpending.longValue());
        mobilityInstance.getAccountSpentPetrol().put(AccountingTypes.m.toString(), dto.petrolSpending.longValue());
        mobilityInstance.getAccountSpentPetrol().put(AccountingTypes.y.toString(), dto.petrolSpending.longValue());

        mobilityInstance.getAccountSpentParts().put(AccountingTypes.w.toString(), dto.partSpending.longValue());
        mobilityInstance.getAccountSpentParts().put(AccountingTypes.m.toString(), dto.partSpending.longValue());
        mobilityInstance.getAccountSpentParts().put(AccountingTypes.y.toString(), dto.partSpending.longValue());

        mobilityInstance.setTotalSpending(0l);
    }
}